This is a copy of the nixpkgs repo, with additional packages defined
for personal use (typically versions of isabelle and HOL).

* 2014-??-?? initial setup

--

Updated/new files:

pkgs/applications/science/logic/myhol   |fails (no hash for fetchgit?)
pkgs/applications/science/logic/hol4k9  |ok                           
pkgs/applications/science/logic/isabelle|ok for isa2013 - needs updating, but probably not worth it, just install from web


--

merge changes from upstream: https://help.github.com/articles/fork-a-repo

https://help.github.com/articles/syncing-a-fork/

git fetch upstream

git merge upstream/master

--

Checkout nixpkgs from github

Add a directory like pkgs/applications/science/logic/myhol/

In this directory, link to e.g. /tmp/l/general/research/code/nix/myhol/default.nix

Change pkgs/top-level/all-packages.nix so that it has an extra clause: myhol = callPackage ../applications/science/logic/myhol { };

put this clause just after the hol clause

Then in the top-level of the github checkout, type:

nix-build -A hol4k9

or 

nix-build -A myhol


finally, ls -al to see where result points, then nix-env -i ./result


TODO: add a polyml 5.5 version to nixpkgs



https://nixos.org/wiki/How_to_add_files_to_the_nix-store


* 2014-08-29 building

Updated/new files:

pkgs/development/compilers/mypolyml     |builds
pkgs/applications/science/logic/myhol   |
pkgs/applications/science/logic/hol4k9  |builds with mypolyml
pkgs/applications/science/logic/isabelle|


nix-build -A hol4k9 gives

Loading system specific functions
Compiling system specific functions (sig sml)
Beginning configuration.
Making tools/mllex/mllex.exe.
Poly/ML 5.5.1 Release
/nix/store/wi8lcasqx0kbabdrdcfymka6r09kp1zh-polyml-5.5.1/lib/libpolyml.a(processes.o): In function `Processes::TestSynchronousRequests(TaskData*)':
(.text+0x1de): undefined reference to `__cxa_allocate_exception'
/nix/store/wi8lcasqx0kbabdrdcfymka6r09kp1zh-polyml-5.5.1/lib/libpolyml.a(processes.o): In function `Processes::TestSynchronousRequests(TaskData*)':
(.text+0x1ed): undefined reference to `__cxa_throw'
...
nix/store/wi8lcasqx0kbabdrdcfymka6r09kp1zh-polyml-5.5.1/lib/libpolyml.a(elfexport.o): In function `ELFExport::exportStore()':
(.text+0x1126): undefined reference to `operator delete[](void*)'
/nix/store/wi8lcasqx0kbabdrdcfymka6r09kp1zh-polyml-5.5.1/lib/libpolyml.a(elfexport.o):(.rodata._ZTI9ELFExport[_ZTI9ELFExport]+0x0): undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info'
/nix/store/wi8lcasqx0kbabdrdcfymka6r09kp1zh-polyml-5.5.1/lib/libpolyml.a(elfexport.o):(.eh_frame+0x113): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
Failed to build mllex.
builder for `/nix/store/wadmgw4jcqnjqvg1hnhcgxshgw4q18l1-hol4-k.9.drv' failed with exit code 1
error: build of `/nix/store/wadmgw4jcqnjqvg1hnhcgxshgw4q18l1-hol4-k.9.drv' failed

looks like libpoly is built strangely, but it is built normally

so this may be a problem with polyml being too new?

maybe a problem with linking in c++ libraries
--

presumably we can go back to the commit where I added hol49 and build with old poly - no this seems to fail in the same way (because using the new poly)

from hol page: "Note also that Poly/ML 5.5.1 does not work unless installed with the --enable-shared flag. This option must be passed to the invocation of configure that is the first step of building Poly/ML from sources."

so the solution is to fork polyml in nixpkgs, and build with that

--

patched mypolyml and hol4k9; everything now builds fine!


something got screwed up when switching branches

trying again...

poly builds fine

same problem with things apparently screwed up, fixed by cd'ing to nixpkgs dir again - possibly git gets confused somehow?
* 2015-04-29 merge with upstream

  - nix-build -A hol4k9 builds fine

* 2015-04-29 update for hol4k10

  - pkgs/applications/science/logic/hol4k10
  - change src to use fetchgit
    - logic/coq/HEAD.nix has an example
      - where does sha256 come from? why isn't this just the commit rev?
        - http://comments.gmane.org/gmane.linux.distributions.nixos/12143
        - use nix-prefetch-git utility
          - we dont' have this; need to update nix itself
        - nix-env -i nix-prefetch-scripts
        - nix-prefetch-git --url https://github.com/HOL-Theorem-Prover/HOL/ --rev HEAD
          - fatal: unable to access 'https://github.com/HOL-Theorem-Prover/HOL/': SSL certificate problem: unable to get local issuer certificate
          - probably because this is using nix git which can't 
          - https://github.com/NixOS/nixpkgs/issues/3382
          - following first suggestion
          - export GIT_SSL_CAINFO=$HOME/.nix-profile/etc/ca-bundle.crt
          - nix prefetch works!
    - https://github.com/HOL-Theorem-Prover/HOL/
    - k10 commit is 7fcca392d98b86bf480b76844e42d6e1e61d1fd2
    - nix-build -A hol4k10 fails

git revision is 7fcca392d98b86bf480b76844e42d6e1e61d1fd2
git human-readable version is -- none --
Commit date is 2014-11-10 15:37:02 +1100
removing `.git'...
building path(s) ‘/nix/store/2drb28zhq7wfyip905bxmwd0yflhi2f8-hol4-k.10’
tar (child): /nix/store/gaidmy0xwvf0w5lm5qhd94g1b02y0fxc-HOL-7fcca39: Cannot read: Is a directory
tar (child): At beginning of tape, quitting now
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
builder for ‘/nix/store/1as9lbmcslpih6bi0xqviv31vlqidc81-hol4-k.10.drv’ failed with exit code 2


    - nix-build --keep-failed
    - debugging following https://nixos.org/wiki/Debugging_a_Nix_Package
    - we have a buildCommand which presumably overrides all inbuilt phases
    - after debugging, fail because of an attempt to write to the store:
ls 
Determining configuration parameters: holdir OS poly polymllibdir 
OS:                 linux
poly:               /nix/store/wcfyz07axlqa8lid1xyf9rpygr4kgwgs-mypolyml-5.5.1/bin/poly
polymllibdir:       /nix/store/wcfyz07axlqa8lid1xyf9rpygr4kgwgs-mypolyml-5.5.1/lib
holdir:             /nix/store/0fmhx2ilwdkl0bzn0baysb403crqjl6k-hol4-k.10/src/HOL-7fcca39
DOT_PATH:           /usr/bin/dot

Configuration will begin with above values.  If they are wrong
press Control-C.

Will continue in 1 seconds.

Loading system specific functions
Exception- Io {cause = SysErr ("Permission denied", SOME EACCES), function = "TextIO.openOut", name = "/nix/store/0fmhx2ilwdkl0bzn0baysb403crqjl6k-hol4-k.10/src/HOL-7fcca39/tools-poly/Holmake/Systeml.sml"} raised
Exception- Io {cause = SysErr ("Permission denied", SOME EACCES), function = "TextIO.openOut", name = "/nix/store/0fmhx2ilwdkl0bzn0baysb403crqjl6k-hol4-k.10/src/HOL-7fcca39/tools-poly/Holmake/Systeml.sml"} raised


** You must do
     poly < tools/smart-configure.sml
** from the root HOL directory

val it = (): unit

    - looks like the premissions of the copied srcs should be relaxed
    - this looks like it will build; it does
    - to install: nix-env -i ./result
* 2015-05-10 nixpkgs and ocaml and createFindlibDestdir

  - pkgs/development/tools/ocaml/findlib/default.nix
  - eg ocaml-base64 installed in ~/.nix-profile/lib/ocaml/4.01.0/site-lib/base64/  (since nix presumably on 4.01.0)
  - nix-env -i ocaml gets 4.02.1
  - but ocaml-base64 reinstall doesn't seem to pick up 
  - having upgraded ocaml, how to upgrade findlib packages?
  - why does nix-env -i ocaml install 4.02.1 instead of default 4.01.0?
    - because we are using the system packages, not super/nixpkgs
  - warning: there are multiple derivations named ‘ocaml-findlib-1.5.3’; using the first one
    - probably we need to select by attribute rather than name
    - nix-env man page: To find out the attribute  paths of available packages, use nix-env -qaP ´*´.
    - nix-env -i -A nixpkgs.ocamlPackages.findlib installs a particular version of findlib, but looks like still 4.01.0
    - where is the nixpkgs that are being used by the system?
      - ~/.nix-defexpr/channels/nixpkgs
      - ~/.nix-defexpr/channels/nixpkgs/pkgs/top-level/all-packages.nix
    - when we ask for all attributes, why can't we see variants of ocaml packages for 4.01, 4.02 etc?
      - eg nixpkgs.ocamlPackages_4_02_1.ocaml-base64
      - there is only nixpkgs.ocamlPackages
      - but nix-env -i -A nixpkgs.ocamlPackages_latest.base64 works and installs 4.02.1 libs
      - https://nixos.org/wiki/Howto_find_a_package_in_NixOS suggests using nox to search for packages, but this doesn't seem to show ocamlPackages_latest etc

* 2015-05-11 nix-shell and ocaml for development env in ocamlenv.nix
* 2015-05-12 packaging p3 on nix

  - added to all-packages.nix
  - added p3 dir, with default.nix
  - nix-build -A ocamlPackages.p3
    - works ok
  - add to ocamlenv
    - need to modify NIX_PATH to work with local fork https://nixos.org/wiki/Nix_Modifying_Packages
    - shell shows p3 and base64 both present
  - what about a standalone nix expression in the repo itself (to control build)? default.nix in p3 repo
  - how easy is it to install nix then install p3 starting from a blank ubuntu image?
    - sudo docker run -i -t  ubuntu:14.04 /bin/bash
    - sudo apt-get update
    - sudo apt-get install curl
    - curl https://nixos.org/nix/install | sh
      - need to be non-root; using dockertest repo, editing mini_ubuntu
    - inside docket:
      - curl https://nixos.org/nix/install | sh
      - nix-binary-tarball-unpack/nix-1.8-x86_64-linux/install: $USER is not set
        - export USER=opam fixes this
      - even though I am the opam user
    - . /home/opam/.nix-profile/etc/profile.d/nix.sh
    - cd /tmp/l/github/super/p3
    - nix-build pulls in everything
    - nix-shell in p3, followed by make, make install; install seems
      to work, but ocamlfind list doesn't show; this is because make
      install puts the libs in the nix store, but they are not merged
      into the user environment
    - building from scratch


  - sometimes get the following error when nix-building in p3:
make[2]: Leaving directory '/tmp/nix-build-p3.drv-0/p3/examples/actions'
/tmp/nix-build-p3.drv-0/p3/examples/../build/earley3_main.native -g grammars/E_EEE.g -f inputs/1_0010.txt
Done items: -1
ocamlbuild -I lexer arith.ml
/nix/store/9a0xlgqq1yc67radpkfmavy59lp547rg-ocaml-4.02.1/bin/ocamllex.opt -q lexer/arith.mll
ocamlbuild -I lexer -cflags '-I /tmp/nix-build-p3.drv-0/p3/examples/../build' -lflags '-I /tmp/nix-build-p3.drv-0/p3/examples/../build p3.cma' lexer_main.byte
Exception
  Sys_error("/tmp/nix-build-p3.drv-0/p3/examples/lexer_main.byte: No such file or directory").
Makefile:19: recipe for target 'lexer' failed
make[1]: *** [lexer] Error 100
make[1]: Leaving directory '/tmp/nix-build-p3.drv-0/p3/examples'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/70sz72xcbz26n0lkh1z905snfnxkaxxz-p3.drv’ failed with exit code 2
error: build of ‘/nix/store/70sz72xcbz26n0lkh1z905snfnxkaxxz-p3.drv’ failed
  - in examples/, make lexer fails
  - seems to be some old files handing around
  - in docker, a clean pull from github would be preferable to
    mounting local dirs which may have cruft, but this means we have to give the sha each time

* 2015-05-12 using nix to test multiple software versions

  - eg suppose we want to test the main and dev versions
  - this works fine in p3/default.nix (p3_2014-04-30)
  - we also want to copy all the build and examples into the destination directory

* 2015-06-11 trying to add new scala eclipse version 4.1

  - need to hash file
  - nix-prefetch-url http://downloads.typesafe.com/scalaide-pack/4.1.0-vfinal-luna-211-20150525/scala-SDK-4.1.0-vfinal-2.11-linux.gtk.x86_64.tar.gz
    - curl: (23) Failed writing body (1713 != 5472)
/home/tr61/.nix-profile/bin/nix-prefetch-url: download of ‘http://downloads.typesafe.com/scalaide-pack/4.1.0-vfinal-luna-211-20150525/scala-SDK-4.1.0-vfinal-2.11-linux.gtk.x86_64.tar.gz’ failed
  - nix-prefetch-url file:///home/tr61/Downloads/scala-SDK-4.1.0-vfinal-2.11-linux.gtk.x86_64.tar.gz
    - same error
  - https://github.com/NixOS/nixpkgs/issues/6828
    - use sha256sum


  - added to super/nixpkgs
  - nix-build -A eclipses.eclipse_scala_sdk_41
  - nix-env -i ./result

* 2015-07-06 packaging mycsv

  - want to make a static version of mycsv, including p1 dependencies
    - just copy and paste the p1 default.nix into .nix/2015-07-06.nix
* 2015-07-28 merge with upstream

https://help.github.com/articles/syncing-a-fork/

* 2015-08-25 merge with upstream
* 2015-08-25 upgrade xpra to use lz4

  - looks like we need to try to use pip with nix
  - https://nixos.org/wiki/Development_Environments#Example_3:_A_simple_impure_environment_to_use_virtualenv.2Fpip_with_nix-shell
  - what is a virtualenv? a python isolation environment


  - compiling python-lz4
    - python setup.py build
    - python setup.py install
  - we have python2.7 and python3.4
  - looks like we can use eg pyxml as a basis to work from


---


nix-build -A python_lz4 gives

> Checking .pth file support in /nix/store/wij7slihixnzb0j6hrsbn540qv15gvsk-python-lz4/lib/python2.7/site-packages/
> /nix/store/ss1aq46xwhnqikq5bjs02sb9xrim2bb3-python-2.7.10/bin/python -E -c pass
> TEST FAILED: /nix/store/wij7slihixnzb0j6hrsbn540qv15gvsk-python-lz4/lib/python2.7/site-packages/ does NOT support .pth files
> error: bad install directory or PYTHONPATH
> 
> You are attempting to install a package to a directory that is not
> on PYTHONPATH and which Python does not read ".pth" files from.  The
> installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /nix/store/wij7slihixnzb0j6hrsbn540qv15gvsk-python-lz4/lib/python2.7/site-packages/
> 
> and your PYTHONPATH environment variable currently contains:
> 
>     '/nix/store/ss1aq46xwhnqikq5bjs02sb9xrim2bb3-python-2.7.10/lib/python2.7/site-packages:/nix/store/5308x1wc8dhsi9vbhxqzpcjcmlprqv6h-python2.7-setuptools-18.0.1/lib/python2.7/site-packages'
> 
> Here are some of your options for correcting the problem:
> 
> * You can choose a different installation directory, i.e., one that is
>   on PYTHONPATH or supports .pth files
> 
> * You can add the installation directory to the PYTHONPATH environment
>   variable.  (It must then also be on PYTHONPATH whenever you run
>   Python and want to use the package(s) you are installing.)
> 
> * You can set up the installation directory to support ".pth" files by
>   using one of the approaches described here:
> 
>   https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations
> 
> Please make the appropriate changes for your system and try again.
> builder for ‘/nix/store/8vrhakr8ri5avwpl1fj4f4b32i9rzmkn-python-lz4.drv’ failed with exit code 1
> error: build of ‘/nix/store/8vrhakr8ri5avwpl1fj4f4b32i9rzmkn-python-lz4.drv’ failed



---


  - xpra built, but doesn't seem to detect lz4: install and enable lzo or lz4 support for better performance
  - test lz4 in nix-shell -A xpra
    - python -c "import lz4" ; echo $? # OK, installed
  - so we need to somehow enable this when building xpra


  - xpra start :100 --compressors=lz4 seems to work from a nix-shell


  - X server already running on display :100
    - how to kill
    - ps aux |grep X
      - shows Ovfb


  - ok, xpra start/xpra attach works
    - everything seems to work ok, but lz4 is not picked up
    - tests/xpra/net/test_lz4.py works ok, but perhaps picking up local lz4?
    - and in a nix-shell --pure this is picked up

  - code in xpra/net/compression seems to be a bit flaky
    - looking for a file named lz4-0.7.0-py2.7-linux-x86_64.egg/lz4.so
    - but we only have the .egg file - perhaps it needs uncompressing? no
    - not clear why this code is not picking up lz4!
      
      
  - ok, how to find out which compressors xpra knows about?
    - need to remove ~/.xpra!
  - need to run xpra with debugging https://www.xpra.org/trac/wiki/Logging


  - moved to package python_lz4 in python-packages
  - we want to somehow propagate ourself when building python_lz4/



  - these two lines in compression.py are wrong:

    LZ4_uncompress = None
    has_lz4 = False

  - make our own github repo, and fix!


  - turns out the lz4 detection in xpra was buggy; hoping 0.15.4 fixes
    - now it seems to detect! success!


  - xpra start ssh:pc1177:100 --compressors=lz4 --start-child=eclipse
    

* 2015-09-09 ocsigenserver

  - get ocaml working again

  - nix-shell for eliom
    - Fatal error: exception Fl_package_base.No_such_package("eliom.client", "") 
      - fixed by adding findlib
    - Fatal error: exception Fl_package_base.No_such_package("ocsigenserver.cookies", "required by `eliom.client'")
      - lib not propagated?

Fatal error: cannot load shared library dllssl_threads_stubs
Reason: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
Makefile:58: recipe for target 'test.byte' failed
make: *** [test.byte] Error 2


  - openssl contains this lib, but not picked up?
    - NIX_LDFLAGS is the var that should be used for linking; how is this used in nix shell?
    - could just be that the compiler should pick this up, but doesn't, so add to hook? but nix_ldflags doesn't contain paths, but linker options
    - fixed by adding openssl/lib to LD_LIBRARY_PATH

Fatal error: cannot load shared library dlllwt-unix_stubs
Reason: dlllwt-unix_stubs.so: cannot open shared object file: No such file or directory
Makefile:58: recipe for target 'test.byte' failed
make: *** [test.byte] Error 2

  - /nix/store/qmw8i4vdm20pnbx28xg29cknnv1w6cjm-ocaml-lwt-2.4.6/lib is in NIX_LDFLAGS, but need /nix/store/qmw8i4vdm20pnbx28xg29cknnv1w6cjm-ocaml-lwt-2.4.6/lib/ocaml/4.01.0/site-lib/lwt/ in LDFLAGS; but this should be found by findlib
    - can we get findlib to show info
      - yes, findlib has this /nix/store/qmw8i4vdm20pnbx28xg29cknnv1w6cjm-ocaml-lwt-2.4.6/lib/ocaml/4.01.0/site-lib/
        - so findlib can find it; 
      - ocamlfind -query -l-format lwt gives
        - -ccopt -L/nix/store/qmw8i4vdm20pnbx28xg29cknnv1w6cjm-ocaml-lwt-2.4.6/lib/ocaml/4.01.0/site-lib/lwt
      - so we need to include all these in LDFLAGS?
    - so when NIX_LDFLAGS is updated, somehow it should reference .../ocaml/4.01.0/site-lib/lwt as well?


  - ocaml package setup hook? http://nixos.org/releases/nixpkgs/nixpkgs-0.12/manual/#chap-stdenv
    - hook addOCamlPath
    - where defined?
      - could be called through envHooks or setupHook
      - but tihs only includes .../site-lib, not subdirs, and only affects OCAMLPATH and OCAMLFIND_DESTDIR
      - how do normal nix packages access libs from other places?
      - how does an ocaml package which depends on another package with a dll get built?



https://github.com/diml/utop CAML_LD_LIBRARY_PATH not set properly

  - yes, this seems to be the case
  - how can we get this 

http://lists.science.uu.nl/pipermail/nix-dev/2015-April/016923.html  fix for CAML_LD_LIBRARY_PATH

development/tools/ocaml/utop/default.nix:    wrapProgram $prog --set CAML_LD_LIBRARY_PATH "${ocaml_lwt}"/lib/ocaml/${ocamlVersion}/site-lib/lwt/:"${lambdaTerm}"/lib/ocaml/${ocamlVersion}/site-lib/lambda-term/:'$CAML_LD_LIBRARY_PATH' --set OCAMLPATH "${ocaml_lwt}"/lib/ocaml/${ocamlVersion}/site-lib:${ocaml_react}/lib/ocaml/${ocamlVersion}/site-lib:${camomile}/lib/ocaml/${ocamlVersion}/site-lib:${zed}/lib/ocaml/${ocamlVersion}/site-lib:${lambdaTerm}/lib/ocaml/${ocamlVersion}/site-lib:"$out"/lib/ocaml/${ocamlVersion}/site-lib:'$OCAMLPATH'


  - so an immediate fix is just to put all this stuff in CAML_LD_LIBRARY_PATH
    - or just install via opam
* 2015-09-10 nixpkgs eliom bug report

make test.opt

ocsigenserver.opt  -c local/etc/client_html/client_html-test.conf
ocsigenserver.opt: main: Fatal - Findlib package sqlite3 [while trying to load ocsigenserver.ext.ocsipersist-sqlite] not found (required by `ocsigenserver.ext.ocsipersist-sqlite'): maybe you forgot <findlib path="..."/>?
Makefile:60: recipe for target 'test.opt' failed
make: *** [test.opt] Error 53

after adding ocaml_sqlite3, everything works

----

_2015-09-16 

make test.opt works

make test.byte doesn't work

----

  - git clone -b fix-ocsigen --depth 1 https://github.com/vbgl/nixpkgs
    - in /tmp


  - NIX_PATH=/tmp nix-shell -pure
    - in client_html

ocsigenserver  -c local/etc/client_html/client_html-test.conf
.ocsigenserver-wrapped: main: Fatal - While loading /nix/store/lg4g6l63j6rra6vg9cf6ilhsmnwv1nav-ocaml-sqlite3-2.0.9/lib/ocaml/4.01.0/site-lib/sqlite3/sqlite3.cma: error loading shared library: dllsqlite3_stubs.so: dllsqlite3_stubs.so: cannot open shared object file: No such file or directory
Makefile:58: recipe for target 'test.byte' failed
make: *** [test.byte] Error 52

fix was to add ocaml_sqlite3 to mkpath

--

commented on nixpkgs issue; will probably be closed shortly
* 2015-10-09 updating nix

* 2015-10-26 adding isabelle 2015

  
pkgs/applications/science/logic/isabelle

* 2015-11-17 debugging texmacs keyboard problems

  - looks like we are missing keyboard bindings

  - grep -R kbd *.scm

src/Edit/Interface/edit_keyboard.cpp


TeXmacs/progs/init-texmacs.scm
TeXmacs/progs/text/text-edit.scm
TeXmacs/progs/text/text-menu.scm


X TeXmacs/progs/text/text-kbd.scm
X TeXmacs/progs/texmacs/keyboard/prefix-kbd.scm

XX TeXmacs/progs/generic/generic-kbd.scm

TeXmacs/progs/generic/generic-edit.scm


---

  - mode seems ok - like-emacs?
---

copied emacs kbd-map section from generic-kbd to .TeXmacs/progs/my-init-buffer.scm, things work fine!

--

export TEXMACS_PATH=/nix/store/00ri6q88bi6l9i6aqmn99ymn1blqsck8-TeXmacs-svn

tr61@pc1177:~$ texmacs
/nix/store/00ri6q88bi6l9i6aqmn99ymn1blqsck8-TeXmacs-svn/bin/.texmacs-wrapped: line 38: exec: texmacs.bin: not found


tr61@pc1177:~$ find /nix/store/00ri6q88bi6l9i6aqmn99ymn1blqsck8-TeXmacs-svn |grep texmacs.bin
/nix/store/00ri6q88bi6l9i6aqmn99ymn1blqsck8-TeXmacs-svn/libexec/TeXmacs/bin/texmacs.bin

probably the datadir is in share which is nixpkgs specific

the executable texmacs.bin appears to be in libexec


the wrapper sets env vars
 
  - prefix="/nix/store/00ri6q88bi6l9i6aqmn99ymn1blqsck8-TeXmacs-svn"
  - TEXMACS_PATH=${prefix}/share/TeXmacs
  - TEXMACS_BIN_PATH=${prefix}/libexec/TeXmacs
  - PATH="$TEXMACS_BIN_PATH/bin:$PATH"
  - exec texmacs.bin


http://www.texmacs.org/tmweb/manual/webman-scheme.en.html - only $TEXMACS_PATH/progs/init-texmacs.scm and TEXMACS_HOME_PATH/progs/my-init-texmacs.scm

and init-texmacs.scm doesn't load generic keyboard? but it looks like it does using lazy-keyboard


---

could be that we just have to restart after selecting look and feel? yes, this fixes things


phew!
* 2016-02-04 need to get ocaml trunk for updated set lib; merge upstream

  - conflict in python packages
  - how to use git to maintain extra stuff ontop of nixpkgs?
    - work in separate branch
    - 
  - how to write small additions to nixpkgs that don't involve copying the entire tree?
    - we do this already in eg sibylfs
    - 

delaying this for now

resolved merge conflicts

updated /tmp/l/github/other/ocaml

added ocaml_trunk in trunk.nix

nix-build -A ocaml_trunk

doesn't know what to do with src=/tmp/l/github/ocaml

presumably we need to change the unpackPhase

an alternative is to include ocaml dir locally, as a link i same dir as trunk.nix

ocaml no longer has ocamlbuild :( hopefully we can use the ocamlbuild
that is already installed by opam
* 2016-03-02 update eclipse-scala


update eclipse/default.nix to add 43

merge upstream/master; clash in xpra

  - nix-build -A eclipses.eclipse_scala_sdk_43
  - nix-env -i ./result
* 2016-04-13 curl CA_BUNDLE

export CURL_CA_BUNDLE=$HOME/.nix-profile/etc/ca-bundle.crt
* 2016-06-01 new thunderbird, 45.0.1 buggy, no search
* 2016-07-14 ci, failing sibylfs build

fetching path ‘/nix/store/jzvdh3bxmcs3xjj20cfh964yy7h18k2h-ocaml-lwt-2.5.2’...

*** Downloading ‘https://cache.nixos.org/nar/0y49b7ipl1dps8a0hyy1a738hb6jqmcwx9qdpf5nnmgxd4g5ymjy.nar.xz’ to ‘/nix/store/jzvdh3bxmcs3xjj20cfh964yy7h18k2h-ocaml-lwt-2.5.2’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2330k  100 2330k    0     0  1219k      0  0:00:01  0:00:01 --:--:-- 1225k

building path(s) ‘/nix/store/77hcsyrhmr70dp720jdhxqfvzfcqyvlr-lem-5b4a168’
exporting https://tomridge@bitbucket.org/tomridge/lem.git (rev 5b4a168) into /nix/store/77hcsyrhmr70dp720jdhxqfvzfcqyvlr-lem-5b4a168
Initialized empty Git repository in /nix/store/77hcsyrhmr70dp720jdhxqfvzfcqyvlr-lem-5b4a168/.git/
remote: Counting objects: 6710, done.        
remote: Compressing objects: 100% (2623/2623), done.        
remote: Total 6710 (delta 5226), reused 5239 (delta 4044)        
Receiving objects: 100% (6710/6710), 7.12 MiB | 3.15 MiB/s, done.
Resolving deltas: 100% (5226/5226), done.
From https://bitbucket.org/tomridge/lem
 * [new branch]      aspects    -> origin/aspects
 * [new branch]      bug_fixes  -> origin/bug_fixes
 * [new branch]      char-literals -> origin/char-literals
 * [new branch]      fs         -> origin/fs
 * [new branch]      inderl_change -> origin/inderl_change
 * [new branch]      library-format -> origin/library-format
 * [new branch]      library-work -> origin/library-work
 * [new branch]      library-work2 -> origin/library-work2
 * [new branch]      library-work3 -> origin/library-work3
 * [new branch]      master     -> origin/master
 * [new branch]      new-features -> origin/new-features
 * [new branch]      numeral-literals -> origin/numeral-literals
 * [new branch]      preprocessing -> origin/preprocessing
 * [new branch]      thtuerk/lemmata -> origin/thtuerk/lemmata
 * [new branch]      word-library -> origin/word-library
 * [new tag]         v.2015-09-07 -> v.2015-09-07
Switched to a new branch 'fetchgit'
removing `.git'...
output path ‘/nix/store/77hcsyrhmr70dp720jdhxqfvzfcqyvlr-lem-5b4a168’ has r:sha256 hash ‘19642yadi089p8si87n0rbn0mwwxyvzjrv33g848gaqy811i0zak’ when ‘0z1chfa2q4h7rdzabyjjh3zhgdafjhjhxyna5hd6q11ns88v7xds’ was expected
cannot build derivation ‘/nix/store/swdk7jfn5qwr7bhl4f260acfgrdqy5zg-lem.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/lj44gfa17j3bqw2r7q4gs7x5ggb5jf0q-ocaml-fd-send-recv-1.0.1.tar.gz’
killing process 19763
cannot build derivation ‘/nix/store/mxfwfpxzjldq9w8a1frkg03ariijy58r-fs_test.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/mxfwfpxzjldq9w8a1frkg03ariijy58r-fs_test.drv’ failed

End



https://github.com/NixOS/nixpkgs/pull/15469 - all the hashes changed


nix-prefetch-url -A hello.src


seems best to debug all these problems in the chroot; perhaps we can avoid hashes? no seems not

we could just edit the files in the overlay; but then we would get clashes with our own nixstore; unless we can already pick up these problems

we still pick up the old hash

to get the new hash?

we are using nix-pref-git
chroot: /nix/store/r6mm3v1wglzhgbpy9vx9vzyd6856b807-nix-prefetch-git/bin/nix-prefetch-git
pc1177: /nix/store/43ppx2dmjwq2p8k0x6px58yyy0sxpyrz-nix-prefetch-git/bin/nix-prefetch-git

why the difference? need to show the dependencies 

 tr61@pc1177:/tmp/l/github/sibylfs_src$ nix-store --query --tree /nix/store/43ppx2dmjwq2p8k0x6px58yyy0sxpyrz-nix-prefetch-git
 /nix/store/43ppx2dmjwq2p8k0x6px58yyy0sxpyrz-nix-prefetch-git
 +---/nix/store/95wmyhk0y60r09b98l6v4vswv5m7xm4q-coreutils-8.25
 |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23
 |   |   +---/nix/store/gygp4inn8w53wy161yy08ilf4kvzw0ki-linux-headers-3.18.14
 |   |   |   +---/nix/store/gygp4inn8w53wy161yy08ilf4kvzw0ki-linux-headers-3.18.14 [...]
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   +---/nix/store/awaqxik06wjw6rmckqlgd4ng94vawic9-acl-2.2.52
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/ignans7cvzxg4mg3qrm4f4ckb0y1dri9-attr-2.4.47
 |   |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   |   +---/nix/store/ignans7cvzxg4mg3qrm4f4ckb0y1dri9-attr-2.4.47 [...]
 |   |   +---/nix/store/awaqxik06wjw6rmckqlgd4ng94vawic9-acl-2.2.52 [...]
 |   +---/nix/store/95wmyhk0y60r09b98l6v4vswv5m7xm4q-coreutils-8.25 [...]
 +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42
 |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42 [...]
 +---/nix/store/g9idnp7fzf06ir918wbhw6sz580i6gbw-nix-1.11.2
 |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   +---/nix/store/0fm4p26lvg6cv97gs3z29y9qr990677q-gzip-1.6
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/0fm4p26lvg6cv97gs3z29y9qr990677q-gzip-1.6 [...]
 |   +---/nix/store/95wmyhk0y60r09b98l6v4vswv5m7xm4q-coreutils-8.25 [...]
 |   +---/nix/store/79mdd0cybnxl64dzfkyaixkp3viw7z06-perl-5.20.3
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/95wmyhk0y60r09b98l6v4vswv5m7xm4q-coreutils-8.25 [...]
 |   |   +---/nix/store/79mdd0cybnxl64dzfkyaixkp3viw7z06-perl-5.20.3 [...]
 |   +---/nix/store/9rz8gxhzf8sw4kf2j2f1grr49w8zx5vj-openssl-1.0.1r
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/9rz8gxhzf8sw4kf2j2f1grr49w8zx5vj-openssl-1.0.1r [...]
 |   +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42 [...]
 |   +---/nix/store/8h6hvrqbhj9zjg83v59ah36j22ljbxh7-curl-7.47.1
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/9rz8gxhzf8sw4kf2j2f1grr49w8zx5vj-openssl-1.0.1r [...]
 |   |   +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42 [...]
 |   |   +---/nix/store/izhhv6wnmbysga5n314sx5xqipdnp4c2-libnghttp2-1.7.1
 |   |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   |   +---/nix/store/izhhv6wnmbysga5n314sx5xqipdnp4c2-libnghttp2-1.7.1 [...]
 |   |   +---/nix/store/wwh7mhwh269sfjkm6k5665b5kgp7jrk2-zlib-1.2.8
 |   |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   |   +---/nix/store/wwh7mhwh269sfjkm6k5665b5kgp7jrk2-zlib-1.2.8 [...]
 |   |   +---/nix/store/zlq1bzf4ilbgp20jll6737m1y1n44d0i-libssh2-1.7.0
 |   |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   |   +---/nix/store/9rz8gxhzf8sw4kf2j2f1grr49w8zx5vj-openssl-1.0.1r [...]
 |   |   |   +---/nix/store/wwh7mhwh269sfjkm6k5665b5kgp7jrk2-zlib-1.2.8 [...]
 |   |   |   +---/nix/store/zlq1bzf4ilbgp20jll6737m1y1n44d0i-libssh2-1.7.0 [...]
 |   |   +---/nix/store/8h6hvrqbhj9zjg83v59ah36j22ljbxh7-curl-7.47.1 [...]
 |   +---/nix/store/ay8cpbxz6xavpapx568c3dyj8spilzfp-gnutar-1.28
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/ay8cpbxz6xavpapx568c3dyj8spilzfp-gnutar-1.28 [...]
 |   +---/nix/store/b8mlryrzy6707imcgdvv3fqqay6yprmx-perl-WWW-Curl-4.17
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/8h6hvrqbhj9zjg83v59ah36j22ljbxh7-curl-7.47.1 [...]
 |   |   +---/nix/store/b8mlryrzy6707imcgdvv3fqqay6yprmx-perl-WWW-Curl-4.17 [...]
 |   +---/nix/store/gjiakvrh8d8pvsagqqb42c6l7hc4gf9l-xz-5.2.2
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/gjiakvrh8d8pvsagqqb42c6l7hc4gf9l-xz-5.2.2 [...]
 |   +---/nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3
 |   |   +---/nix/store/gygp4inn8w53wy161yy08ilf4kvzw0ki-linux-headers-3.18.14 [...]
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/wwh7mhwh269sfjkm6k5665b5kgp7jrk2-zlib-1.2.8 [...]
 |   |   +---/nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3 [...]
 |   +---/nix/store/kak7rqric8p1b7v6q1ai0n03bw9y1v5j-sqlite-3.9.2
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/kak7rqric8p1b7v6q1ai0n03bw9y1v5j-sqlite-3.9.2 [...]
 |   +---/nix/store/ngxxl0h2nksvp92czijdqn1gwcnw64bd-perl-DBI-1.634
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/79mdd0cybnxl64dzfkyaixkp3viw7z06-perl-5.20.3 [...]
 |   |   +---/nix/store/ngxxl0h2nksvp92czijdqn1gwcnw64bd-perl-DBI-1.634 [...]
 |   +---/nix/store/rkqlbbr2mpglbfsysf8m9igngyz9cl45-boehm-gc-7.2f
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3 [...]
 |   |   +---/nix/store/rkqlbbr2mpglbfsysf8m9igngyz9cl45-boehm-gc-7.2f [...]
 |   +---/nix/store/rrjvbqna950sjwfaqqaqxqm0k7al15az-libsodium-1.0.8
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3 [...]
 |   |   +---/nix/store/rrjvbqna950sjwfaqqaqxqm0k7al15az-libsodium-1.0.8 [...]
 |   +---/nix/store/wdbwdwjhmr5451cli44yvrs3grwwz84g-perl-DBD-SQLite-1.48
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/kak7rqric8p1b7v6q1ai0n03bw9y1v5j-sqlite-3.9.2 [...]
 |   |   +---/nix/store/ngxxl0h2nksvp92czijdqn1gwcnw64bd-perl-DBI-1.634 [...]
 |   |   +---/nix/store/wdbwdwjhmr5451cli44yvrs3grwwz84g-perl-DBD-SQLite-1.48 [...]
 |   +---/nix/store/ymjf7jwbg1xidafhksi9csqzfsb02zqx-bzip2-1.0.6
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/ymjf7jwbg1xidafhksi9csqzfsb02zqx-bzip2-1.0.6 [...]
 |   +---/nix/store/g9idnp7fzf06ir918wbhw6sz580i6gbw-nix-1.11.2 [...]
 +---/nix/store/h1s9586w90h80r1na0wsixy9yqyjlj0q-git-2.7.1
 |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   +---/nix/store/0fm4p26lvg6cv97gs3z29y9qr990677q-gzip-1.6 [...]
 |   +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42 [...]
 |   +---/nix/store/2bvpy3bw05a5mvybay6ph501bmf6s05z-gettext-0.19.7
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42 [...]
 |   |   +---/nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3 [...]
 |   |   +---/nix/store/2bvpy3bw05a5mvybay6ph501bmf6s05z-gettext-0.19.7 [...]
 |   +---/nix/store/79mdd0cybnxl64dzfkyaixkp3viw7z06-perl-5.20.3 [...]
 |   +---/nix/store/9rz8gxhzf8sw4kf2j2f1grr49w8zx5vj-openssl-1.0.1r [...]
 |   +---/nix/store/wwh7mhwh269sfjkm6k5665b5kgp7jrk2-zlib-1.2.8 [...]
 |   +---/nix/store/8h6hvrqbhj9zjg83v59ah36j22ljbxh7-curl-7.47.1 [...]
 |   +---/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/95wmyhk0y60r09b98l6v4vswv5m7xm4q-coreutils-8.25 [...]
 |   |   +---/nix/store/9rz8gxhzf8sw4kf2j2f1grr49w8zx5vj-openssl-1.0.1r [...]
 |   |   +---/nix/store/idm1067y9i6m87crjqrbamdsq2ma5r7p-bash-4.3-p42 [...]
 |   |   +---/nix/store/wwh7mhwh269sfjkm6k5665b5kgp7jrk2-zlib-1.2.8 [...]
 |   |   +---/nix/store/ymjf7jwbg1xidafhksi9csqzfsb02zqx-bzip2-1.0.6 [...]
 |   |   +---/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11 [...]
 |   +---/nix/store/bi5p7jq0xvha3aqlzkyh2yziwl19nh78-expat-2.1.0
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/bi5p7jq0xvha3aqlzkyh2yziwl19nh78-expat-2.1.0 [...]
 |   +---/nix/store/y50jbamh4iw1nhgyi3xdxg14fd8hslpg-gnugrep-2.22
 |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   +---/nix/store/1vvq1z30z211qh5vpsjf3ppvk0crcm53-pcre-8.38
 |   |   |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   |   |   +---/nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3 [...]
 |   |   |   +---/nix/store/1vvq1z30z211qh5vpsjf3ppvk0crcm53-pcre-8.38 [...]
 |   |   +---/nix/store/y50jbamh4iw1nhgyi3xdxg14fd8hslpg-gnugrep-2.22 [...]
 |   +---/nix/store/h1s9586w90h80r1na0wsixy9yqyjlj0q-git-2.7.1 [...]
 +---/nix/store/wgy9kf7z23wd422nirlylq0whhy49ipw-gnused-4.2.2
 |   +---/nix/store/pv9sza1cf2kpawck7wbwdnhlip5h57lg-glibc-2.23 [...]
 |   +---/nix/store/wgy9kf7z23wd422nirlylq0whhy49ipw-gnused-4.2.2 [...]
 +---/nix/store/43ppx2dmjwq2p8k0x6px58yyy0sxpyrz-nix-prefetch-git [...]
 
 
 /nix/store/r6mm3v1wglzhgbpy9vx9vzyd6856b807-nix-prefetch-git
 +---/nix/store/1fy1p7366rr924m7k5yidhlk5sv9r6vw-coreutils-8.25
 |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/9yvanjh5jjvwxp5xa85b09mfjzrq8bvc-acl-2.2.52
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/fdjbs7yrxrwx0151f4n9jpfxvz5gilbq-attr-2.4.47
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/fdjbs7yrxrwx0151f4n9jpfxvz5gilbq-attr-2.4.47 [...]
 |   |   +---/nix/store/9yvanjh5jjvwxp5xa85b09mfjzrq8bvc-acl-2.2.52 [...]
 |   +---/nix/store/1fy1p7366rr924m7k5yidhlk5sv9r6vw-coreutils-8.25 [...]
 +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42
 |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 +---/nix/store/bsvcv4add76skp3j5px7iidpzw9krfk3-gnused-4.2.2
 |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/bsvcv4add76skp3j5px7iidpzw9krfk3-gnused-4.2.2 [...]
 +---/nix/store/df88l3yqc9fl1qgy4rmaldzci7hjb3vm-git-2.9.0
 |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/3l8ggzkjyxx83y74kfi5bpv4cxm4nifx-expat-2.2.0
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/3l8ggzkjyxx83y74kfi5bpv4cxm4nifx-expat-2.2.0 [...]
 |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   +---/nix/store/7gkk2s4q89fjnrkpmkaqs2rsxxj8l4ny-gettext-0.19.7
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   |   +---/nix/store/hyx21jmjsy3ph3n65zxsfhwzm4r7yhkq-gcc-5.4.0-lib
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/hyx21jmjsy3ph3n65zxsfhwzm4r7yhkq-gcc-5.4.0-lib [...]
 |   |   +---/nix/store/7gkk2s4q89fjnrkpmkaqs2rsxxj8l4ny-gettext-0.19.7 [...]
 |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/aqc6s8l5rzxjv0yrgwj41c00kllxsyhl-openssh-7.2p2
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   |   +---/nix/store/fj9zz3carpk8nmwi0gh3rrzf9kq15lya-ncurses-5.9
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/fj9zz3carpk8nmwi0gh3rrzf9kq15lya-ncurses-5.9 [...]
 |   |   +---/nix/store/8ybbk0y5bj0fwfa4wfqhig8c03jsabj9-libedit-20150325-3.1
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/fj9zz3carpk8nmwi0gh3rrzf9kq15lya-ncurses-5.9 [...]
 |   |   |   +---/nix/store/0x61nl1fls6ab5ksk90kp12a9ccrs6l3-ncurses-5.9-dev
 |   |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   |   |   |   +---/nix/store/fj9zz3carpk8nmwi0gh3rrzf9kq15lya-ncurses-5.9 [...]
 |   |   |   |   +---/nix/store/hwg9ffhlih4gznmzbpkxipfnm51vm9i9-ncurses-5.9-man
 |   |   |   |   +---/nix/store/0x61nl1fls6ab5ksk90kp12a9ccrs6l3-ncurses-5.9-dev [...]
 |   |   |   +---/nix/store/8ybbk0y5bj0fwfa4wfqhig8c03jsabj9-libedit-20150325-3.1 [...]
 |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8 [...]
 |   |   +---/nix/store/w7mbvxliq6yr8hvagczgifd6jsg63bhg-linux-pam-1.2.1
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   |   |   +---/nix/store/0lf9nlr7znkczpgq8w1abrzm5m81f2r4-cracklib-2.9.6
 |   |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   |   |   |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8 [...]
 |   |   |   |   +---/nix/store/0lf9nlr7znkczpgq8w1abrzm5m81f2r4-cracklib-2.9.6 [...]
 |   |   |   +---/nix/store/w7mbvxliq6yr8hvagczgifd6jsg63bhg-linux-pam-1.2.1 [...]
 |   |   +---/nix/store/aqc6s8l5rzxjv0yrgwj41c00kllxsyhl-openssh-7.2p2 [...]
 |   +---/nix/store/bf2yh8f1r8hpjmnr1sy9mnhw0dbm5hra-gnugrep-2.25
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/13cbz82vfdvy60vx6ghnjr7057wq1bdx-pcre-8.38
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/13cbz82vfdvy60vx6ghnjr7057wq1bdx-pcre-8.38 [...]
 |   |   +---/nix/store/bf2yh8f1r8hpjmnr1sy9mnhw0dbm5hra-gnugrep-2.25 [...]
 |   +---/nix/store/bsjqscdpv9zgikghg6pbwn0l4cqd6gxx-curl-7.47.1
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8 [...]
 |   |   +---/nix/store/rxs1q2pd2683m6fjrkfmg9bhapxvgm6r-nghttp2-1.10.0-lib
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/rxs1q2pd2683m6fjrkfmg9bhapxvgm6r-nghttp2-1.10.0-lib [...]
 |   |   +---/nix/store/yys5j2k2l92cwz4dq3m9pim7v091qxaf-libssh2-1.7.0
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   |   |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8 [...]
 |   |   |   +---/nix/store/yys5j2k2l92cwz4dq3m9pim7v091qxaf-libssh2-1.7.0 [...]
 |   |   +---/nix/store/bsjqscdpv9zgikghg6pbwn0l4cqd6gxx-curl-7.47.1 [...]
 |   +---/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/12vi3yn4ws0285602a9qlkq4ha5qzv5a-bzip2-1.0.6.0.1
 |   |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   |   +---/nix/store/12vi3yn4ws0285602a9qlkq4ha5qzv5a-bzip2-1.0.6.0.1 [...]
 |   |   +---/nix/store/1fy1p7366rr924m7k5yidhlk5sv9r6vw-coreutils-8.25 [...]
 |   |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8 [...]
 |   |   +---/nix/store/crvgrgvya6ggj67qknbs6aq7lp03n9v1-python-2.7.11 [...]
 |   +---/nix/store/kzj0br631km4d8arymlwpm9g2iimsn9h-perl-5.22.2
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/1fy1p7366rr924m7k5yidhlk5sv9r6vw-coreutils-8.25 [...]
 |   |   +---/nix/store/kzj0br631km4d8arymlwpm9g2iimsn9h-perl-5.22.2 [...]
 |   +---/nix/store/yfsixzkvj0izckkrg805093n0f3cfl1b-gzip-1.8
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/df88l3yqc9fl1qgy4rmaldzci7hjb3vm-git-2.9.0 [...]
 +---/nix/store/jz75mzicpfb9z3i7zzqn0x80rn9shn7v-nix-1.11.2
 |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   +---/nix/store/12vi3yn4ws0285602a9qlkq4ha5qzv5a-bzip2-1.0.6.0.1 [...]
 |   +---/nix/store/1fy1p7366rr924m7k5yidhlk5sv9r6vw-coreutils-8.25 [...]
 |   +---/nix/store/3fw6nx8p05a4sc742srawh5dnchnkjs9-sqlite-3.12.2
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/3fw6nx8p05a4sc742srawh5dnchnkjs9-sqlite-3.12.2 [...]
 |   +---/nix/store/3p2j46p81xx28g1bpc9zr70dml9xb877-bash-4.3-p42 [...]
 |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   +---/nix/store/bsjqscdpv9zgikghg6pbwn0l4cqd6gxx-curl-7.47.1 [...]
 |   +---/nix/store/f2kxd5zwa1n8wf1ih5c1wid0m3zd2848-xz-5.2.2
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/f2kxd5zwa1n8wf1ih5c1wid0m3zd2848-xz-5.2.2 [...]
 |   +---/nix/store/c727f8wbmbwla3rcz129m5qwmn9r2b2w-xz-5.2.2-bin
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/f2kxd5zwa1n8wf1ih5c1wid0m3zd2848-xz-5.2.2 [...]
 |   +---/nix/store/dsvk68vkvbj7q9c2n9sz9aypx403lbaq-curl-7.47.1-bin
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   |   +---/nix/store/h6a5qnn3alf2xq0k7d1hzqqbss9d028x-zlib-1.2.8 [...]
 |   |   +---/nix/store/bsjqscdpv9zgikghg6pbwn0l4cqd6gxx-curl-7.47.1 [...]
 |   +---/nix/store/hsi2840cjvxhcq2b39jccmmrzwxfcyrf-bzip2-1.0.6.0.1-bin
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/12vi3yn4ws0285602a9qlkq4ha5qzv5a-bzip2-1.0.6.0.1 [...]
 |   +---/nix/store/hyx21jmjsy3ph3n65zxsfhwzm4r7yhkq-gcc-5.4.0-lib [...]
 |   +---/nix/store/kzj0br631km4d8arymlwpm9g2iimsn9h-perl-5.22.2 [...]
 |   +---/nix/store/ikqhc3vvs76rzpk9s613mxsav3v6lsy5-perl-DBI-1.636
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/kzj0br631km4d8arymlwpm9g2iimsn9h-perl-5.22.2 [...]
 |   |   +---/nix/store/ikqhc3vvs76rzpk9s613mxsav3v6lsy5-perl-DBI-1.636 [...]
 |   +---/nix/store/kmrf82idr16gy8nmqz0z53gml8j9vj6f-boehm-gc-7.2f
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/hyx21jmjsy3ph3n65zxsfhwzm4r7yhkq-gcc-5.4.0-lib [...]
 |   |   +---/nix/store/kmrf82idr16gy8nmqz0z53gml8j9vj6f-boehm-gc-7.2f [...]
 |   +---/nix/store/ksg1ql50c8snmc001djwdvisxz4yhpv2-perl-WWW-Curl-4.17
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/bsjqscdpv9zgikghg6pbwn0l4cqd6gxx-curl-7.47.1 [...]
 |   |   +---/nix/store/ksg1ql50c8snmc001djwdvisxz4yhpv2-perl-WWW-Curl-4.17 [...]
 |   +---/nix/store/px11lqr3abyk3sivdjs4slz07y8hq1ix-libsodium-1.0.10
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/px11lqr3abyk3sivdjs4slz07y8hq1ix-libsodium-1.0.10 [...]
 |   +---/nix/store/qq4z56l11xhzc3w9paqamnprllalmlph-perl-DBD-SQLite-1.48
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/3fw6nx8p05a4sc742srawh5dnchnkjs9-sqlite-3.12.2 [...]
 |   |   +---/nix/store/ikqhc3vvs76rzpk9s613mxsav3v6lsy5-perl-DBI-1.636 [...]
 |   |   +---/nix/store/qq4z56l11xhzc3w9paqamnprllalmlph-perl-DBD-SQLite-1.48 [...]
 |   +---/nix/store/vvsh5bbjj9rmfg99l87iqv8ccnbamqbg-gnutar-1.29
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/9yvanjh5jjvwxp5xa85b09mfjzrq8bvc-acl-2.2.52 [...]
 |   |   +---/nix/store/vvsh5bbjj9rmfg99l87iqv8ccnbamqbg-gnutar-1.29 [...]
 |   +---/nix/store/wgi33skswnb2d5agi2790lzlj2ynq2xh-openssl-1.0.2h-bin
 |   |   +---/nix/store/763vw2zyc9434dj7rw6c2kczj0blvssy-glibc-2.23 [...]
 |   |   +---/nix/store/a71i75jckbpfqknli6yqrhjg80ipalz4-openssl-1.0.2h [...]
 |   |   +---/nix/store/kzj0br631km4d8arymlwpm9g2iimsn9h-perl-5.22.2 [...]
 |   +---/nix/store/yfsixzkvj0izckkrg805093n0f3cfl1b-gzip-1.8 [...]
 |   +---/nix/store/jz75mzicpfb9z3i7zzqn0x80rn9shn7v-nix-1.11.2 [...]
 +---/nix/store/r6mm3v1wglzhgbpy9vx9vzyd6856b807-nix-prefetch-git [...]
 
 


OK, so clearly the dependencies are different; what could cause this? 

pc1177: warning: there are multiple derivations named ‘nix-prefetch-git’; using the first one

and it looks like we have nixos in .nix-def-expr, but only nix in .nix-channels

want to reinitialize channels

nix-channel --remove nixos
nix-channel --update

this works, and we are now up to date

so we can use nix-prefetch-git to check hashes

first, we might try running ci again; it works; probably because it is reusing lem source

nix-store --delete /nix/store/77hcsyrhmr70dp720jdhxqfvzfcqyvlr-lem-5b4a168

nix-store --delete  /nix/store/swdk7jfn5qwr7bhl4f260acfgrdqy5zg-lem.drv   /nix/store/av0a0a90b8j49li7jy46papqgixsl27q-fs_spec.drv   /nix/store/mxfwfpxzjldq9w8a1frkg03ariijy58r-fs_test.drv


finding garbage collector roots...
error: cannot delete path ‘/nix/store/av0a0a90b8j49li7jy46papqgixsl27q-fs_spec.drv’ since it is still alive
0 store paths deleted, 0.00 MiB freed

 nix-store -q --roots /nix/store/av0a0a90b8j49li7jy46papqgixsl27q-fs_spec.drv

what is needed is a way to rebuild all dependencies


nix-store --verify --check-contents --repair to try to force recomputing of hashes (and thus, rebuilding)


gc roots:

tr61@pc1177:/tmp/l/github/ci$ ls -al /nix/var/nix/gcroots/auto/
total 52
drwxr-xr-x 2 tr61 tr61 40960 Jul 14 12:32 .
drwxr-xr-x 3 tr61 tr61  4096 Nov 29  2013 ..
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 12:22 0291wfyka7sdicw6nhh0bmg62b7a46j2 -> /tmp/1955098240787528832/p1/result
lrwxrwxrwx 1 tr61 tr61    45 Jun 28 10:39 53a5ixgpkdj4izflc8qw3w0bzrfdsjnl -> /tmp/3864640332318516801/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    41 Jul 10  2015 77d6fydbiqbncvz79447aqv0j9r1vsy1 -> /mnt/sdb1/tom/bitbucket/fs.copy/fs/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 12:22 84ixka0yddidjc4bkl3n3xsgdyrfsjj0 -> /tmp/5838431124889032473/e3/result
lrwxrwxrwx 1 tr61 tr61    44 Jul 14 12:10 bn8hyqvpcibyn0y8b84dxwxrpvdfqm39 -> /tmp/939292289461763401/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    35 May 31 12:00 cq5q5sj9zfp4wbl28lw74drh4cr5d0kf -> /mnt/sdb1/tom/github/nixpkgs/result
lrwxrwxrwx 1 tr61 tr61    33 Aug 20  2015 crfm2qf4v6mxb8q24ai3d5m353n87ljh -> /mnt/sdb1/tom/bitbucket/fs/result
lrwxrwxrwx 1 tr61 tr61    34 Jun 28 10:39 gj6fjhrla170zhc41vli4p1ga7cwyd6h -> /tmp/4888969021012080192/e3/result
lrwxrwxrwx 1 tr61 tr61    39 Jun 10 13:39 ig5nsfk1q61vmqkjqkykgh8iymkj870c -> /mnt/sdb1/tom/github/sibylfs_src/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 12:21 ivn7hx15aaa747rsc54qrwdda4p9rwaa -> /tmp/9018013846173287412/p1/result
lrwxrwxrwx 1 tr61 tr61    40 Jul 22  2015 jfsyan3pgs8rimf11dkrqbil395r0hk7 -> /mnt/sdb1/tom/bitbucket/fs_nix/fs/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 10:45 jla70213swqqj0f1iys140g56blaig43 -> /tmp/4099423361335433101/e3/result
lrwxrwxrwx 1 tr61 tr61    45 Jul 14 12:22 knwafv5r5387hc4717gzx0d0zgslmal5 -> /tmp/5574822705425426715/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    43 Jul 14 10:45 l7jnr4rdr9fgc8hi76407wwglckyjr13 -> /tmp/6767562389702169065/sibylfs_src/result
lrwxrwxrwx 1 tr61 tr61    33 Jul 14 12:21 l8amksk2hks5hd13hmkba8p28ix0h91g -> /tmp/414003158546678572/e3/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 12:09 lkp30sc8ipj10y85c9f9aapg47adrgmg -> /tmp/2646051097056415794/e3/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 12:09 lr0qj45vxbb9p2xrq5z9rkshww9rdrhx -> /tmp/6690760006279164662/p1/result
lrwxrwxrwx 1 tr61 tr61    43 Jul 14 12:22 m4qlxrf39lzkiz16aa6fd0l160km2rvh -> /tmp/2231402612253777790/sibylfs_src/result
lrwxrwxrwx 1 tr61 tr61    34 Jun 28 10:39 pd3akc6s7s2051v8fjj9yp8sz13dl3r4 -> /tmp/7431564068082728580/p1/result
lrwxrwxrwx 1 tr61 tr61    70 Mar 22 10:58 pglfv1wqwwhaf9d7jh85fdahi0kbrgsq -> /mnt/sda5/tom/scratch/l/Dropbox/scala_workspace/ocamldep_to_dot/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 10:45 pz0x57j42bic3j62jbbj7v0dff9pp74g -> /tmp/6221190369090361282/p1/result
lrwxrwxrwx 1 tr61 tr61    45 Jul 14 10:45 qnx41cl2lhzk2xkpxkwwzhj4kjamr4df -> /tmp/4528884286528857610/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    45 Jul 14 12:20 rx7wb8h6m7vvn5l2s4w7w06qz54q58ab -> /tmp/4507509463503805265/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    34 Jul 14 12:20 sbmzc0zyq852bn2if3crfc4qllarcxbn -> /tmp/1307128883077128996/p1/result
lrwxrwxrwx 1 tr61 tr61    41 Jun 16 13:47 v8k05ddf44p774hzdxyd46rvj6w0gkln -> /mnt/sdb1/tom/github/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    45 Jul 14 12:21 wrnn0z7m9fhqc4yg0cpvjdxv05aarj7j -> /tmp/4560248760152094799/simple_earley/result
lrwxrwxrwx 1 tr61 tr61    33 Jul 14 12:20 xny7w5bmd1gis83028b0jzmak54x87xz -> /tmp/512601027621631683/e3/result
lrwxrwxrwx 1 tr61 tr61    43 Jun 28 10:39 xvfadjz83qs3a8jjxz4n5gx6i4k3m8r9 -> /tmp/5656238319337842123/sibylfs_src/result




rm -f /mnt/sda5/tom/scratch/l/Dropbox/scala_workspace/ocamldep_to_dot/result
rm -f /mnt/sdb1/tom/bitbucket/fs.copy/fs/result
rm -f /mnt/sdb1/tom/bitbucket/fs/result
rm -f /mnt/sdb1/tom/bitbucket/fs_nix/fs/result
rm -f /mnt/sdb1/tom/github/nixpkgs/result
rm -f /mnt/sdb1/tom/github/sibylfs_src/result
rm -f /mnt/sdb1/tom/github/simple_earley/result
rm -f /tmp/1307128883077128996/p1/result
rm -f /tmp/1955098240787528832/p1/result
rm -f /tmp/2231402612253777790/sibylfs_src/result
rm -f /tmp/2646051097056415794/e3/result
rm -f /tmp/3864640332318516801/simple_earley/result
rm -f /tmp/4099423361335433101/e3/result
rm -f /tmp/414003158546678572/e3/result
rm -f /tmp/4507509463503805265/simple_earley/result
rm -f /tmp/4528884286528857610/simple_earley/result
rm -f /tmp/4560248760152094799/simple_earley/result
rm -f /tmp/4888969021012080192/e3/result
rm -f /tmp/512601027621631683/e3/result
rm -f /tmp/5574822705425426715/simple_earley/result
rm -f /tmp/5656238319337842123/sibylfs_src/result
rm -f /tmp/5838431124889032473/e3/result
rm -f /tmp/6221190369090361282/p1/result
rm -f /tmp/6690760006279164662/p1/result
rm -f /tmp/6767562389702169065/sibylfs_src/result
rm -f /tmp/7431564068082728580/p1/result
rm -f /tmp/9018013846173287412/p1/result
rm -f /tmp/939292289461763401/simple_earley/result


nix-store --gc

yay! now we get the same error on pc1177

Switched to a new branch 'fetchgit'
removing `.git'...
output path ‘/nix/store/77hcsyrhmr70dp720jdhxqfvzfcqyvlr-lem-5b4a168’ has r:sha256 hash ‘19642yadi089p8si87n0rbn0mwwxyvzjrv33g848gaqy811i0zak’ when ‘0z1chfa2q4h7rdzabyjjh3zhgdafjhjhxyna5hd6q11ns88v7xds’ was expected
cannot build derivation ‘/nix/store/swdk7jfn5qwr7bhl4f260acfgrdqy5zg-lem.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/lj44gfa17j3bqw2r7q4gs7x5ggb5jf0q-ocaml-fd-send-recv-1.0.1.tar.gz’
killing process 11213
cannot build derivation ‘/nix/store/mxfwfpxzjldq9w8a1frkg03ariijy58r-fs_test.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/mxfwfpxzjldq9w8a1frkg03ariijy58r-fs_test.drv’ failed

End


OK, now everything works again


